### ISSUE TITLE
Provide a Maven example project

### ISSUE THREAD

**Issue by FDelporte** [SupernautApp/SupernautFX#9]
Would be great if a Maven getting-started would be available!
Maybe I can help if the library is available in the mvnrepository?

**Comment by msgilligan** [comment]
Hi @FDelporte so great to hear from you here! Funny, a maven sample is what I was working on yesterday and the day before. I would love your help with Maven, because I don't know it that well.

I just published what I have so far: [SupernautApp/supernaut-fx-sample-maven](https://github.com/SupernautApp/supernaut-fx-sample-maven).

Here's the current status:

* Working targets: `javafx:run`, `client:build`, `client:run`
* Not working: `javafx:jlink` (because I don't know how to configure the equivalent tweaking to what the Badass JLink Gradle Plugin is doing)

So the current situation is with Gradle I can produce a jlink/jpackage app and with Maven I can produce a Graal native image. I would like to be able to do both types of builds with both build tools.

I want to Publish Supernaut.FX to Maven Central, but haven't done it yet (and the JCenter shutdown makes this high-priority) for now you can use this repo:

```
    <repository>
      <id>bintray.supernautapp</id>
      <url>https://dl.bintray.com/supernautapp/maven</url>
    </repository>
```

Note that I have changes in `master` that provide support for Graal native-image as well as enable non-modular ServiceLoader to find `MicronautFxLauncher`. I hope to release version 0.1.1 with these changes very soon.

**Comment by FDelporte** [comment]
Great work! and ai ai jlink-problems ;-) will try to investigate and if I can provide feedback...

**Comment by msgilligan** [comment]
@FDelporte version 0.1.1 is released, so the Maven sample should now build without a local snapshot.

> will try to investigate and if I can provide feedback...

Thanks!

**Comment by msgilligan** [comment]
> ai ai jlink-problems ;-) 

See Issue #10 for a possible solution to some of the jlink problems.

**Comment by msgilligan** [comment]
@FDelporte I just updated the Maven sample to Supernaut.FX 0.1.2, Micronaut 2.4.0, JavaFX 16, and `jakarta.inject`.

* https://github.com/SupernautApp/supernaut-fx-sample-maven/commit/d079d41ab1d29ff4048882ace22dc1adc40042c4
* https://github.com/SupernautApp/supernaut-fx-sample-maven/commit/4fa3908927c7fb32896b51377957135418b8b645

**Comment by msgilligan** [comment]
I'm going to close this issue as [SupernautApp/supernaut-fx-sample-maven](https://github.com/SupernautApp/supernaut-fx-sample-maven) exists and has it's own issue DB that we can use to track any issues.
